// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AgentAckRequest defines model for AgentAckRequest.
type AgentAckRequest struct {
	Id     string `json:"id"`
	ScanId string `json:"scan_id"`
}

// AgentPollTask defines model for AgentPollTask.
type AgentPollTask struct {
	Id              string  `json:"id"`
	ReportingConfig *string `json:"reporting_config,omitempty"`
	ScanConfig      *string `json:"scan_config,omitempty"`
	ScanId          string  `json:"scan_id"`
	Value           []byte  `json:"value"`
}

// LocalAgent defines model for LocalAgent.
type LocalAgent struct {
	Arch       string      `json:"arch"`
	CpuCores   int         `json:"cpu_cores"`
	CreatedAt  time.Time   `json:"created_at"`
	Hostname   string      `json:"hostname"`
	Id         string      `json:"id"`
	LastPingAt time.Time   `json:"last_ping_at"`
	MachineId  string      `json:"machine_id"`
	MemoryGb   int         `json:"memory_gb"`
	Os         string      `json:"os"`
	Status     interface{} `json:"status"`
	UpdatedAt  time.Time   `json:"updated_at"`
	Uptime     *string     `json:"uptime,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string  `json:"code"`
	Error   *string `json:"error,omitempty"`
	ErrorId *string `json:"error_id,omitempty"`
	Kind    string  `json:"kind"`
	Message string  `json:"message"`
	Param   *string `json:"param,omitempty"`
	Status  int     `json:"status"`
}

// GetAgents defines model for GetAgents.
type GetAgents struct {
	CurrentPage  int          `json:"current_page"`
	Data         []LocalAgent `json:"data"`
	ResultCount  int          `json:"result_count"`
	TotalPages   int          `json:"total_pages"`
	TotalResults int          `json:"total_results"`
}

// GetAgentsParams defines parameters for GetAgents.
type GetAgentsParams struct {
	UserId int64 `form:"user_id" json:"user_id"`

	// Offset The number of items to skip before starting to collect the result set
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// PostAgentRegisterJSONBody defines parameters for PostAgentRegister.
type PostAgentRegisterJSONBody struct {
	Arch      string `json:"arch"`
	CpuCores  int    `json:"cpu_cores"`
	Hostname  string `json:"hostname"`
	MachineId string `json:"machine_id"`
	MemoryGb  int    `json:"memory_gb"`
	Os        string `json:"os"`
}

// PostAgentRegisterParams defines parameters for PostAgentRegister.
type PostAgentRegisterParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// DeleteAgentsIdParams defines parameters for DeleteAgentsId.
type DeleteAgentsIdParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// GetAgentsIdParams defines parameters for GetAgentsId.
type GetAgentsIdParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// PostAgentsIdAckJSONBody defines parameters for PostAgentsIdAck.
type PostAgentsIdAckJSONBody = []AgentAckRequest

// PostAgentsIdAckParams defines parameters for PostAgentsIdAck.
type PostAgentsIdAckParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// PostAgentsIdPingParams defines parameters for PostAgentsIdPing.
type PostAgentsIdPingParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// GetAgentsIdPollParams defines parameters for GetAgentsIdPoll.
type GetAgentsIdPollParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
	Count  *int  `form:"count,omitempty" json:"count,omitempty"`
}

// PostAgentsIdResultsJSONBody defines parameters for PostAgentsIdResults.
type PostAgentsIdResultsJSONBody = [][]byte

// PostAgentsIdResultsParams defines parameters for PostAgentsIdResults.
type PostAgentsIdResultsParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// PostAgentRegisterJSONRequestBody defines body for PostAgentRegister for application/json ContentType.
type PostAgentRegisterJSONRequestBody PostAgentRegisterJSONBody

// PostAgentsIdAckJSONRequestBody defines body for PostAgentsIdAck for application/json ContentType.
type PostAgentsIdAckJSONRequestBody = PostAgentsIdAckJSONBody

// PostAgentsIdResultsJSONRequestBody defines body for PostAgentsIdResults for application/json ContentType.
type PostAgentsIdResultsJSONRequestBody = PostAgentsIdResultsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAgents request
	GetAgents(ctx context.Context, params *GetAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAgentRegisterWithBody request with any body
	PostAgentRegisterWithBody(ctx context.Context, params *PostAgentRegisterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAgentRegister(ctx context.Context, params *PostAgentRegisterParams, body PostAgentRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAgentsId request
	DeleteAgentsId(ctx context.Context, id string, params *DeleteAgentsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAgentsId request
	GetAgentsId(ctx context.Context, id string, params *GetAgentsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAgentsIdAckWithBody request with any body
	PostAgentsIdAckWithBody(ctx context.Context, id string, params *PostAgentsIdAckParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAgentsIdAck(ctx context.Context, id string, params *PostAgentsIdAckParams, body PostAgentsIdAckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAgentsIdPing request
	PostAgentsIdPing(ctx context.Context, id string, params *PostAgentsIdPingParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAgentsIdPoll request
	GetAgentsIdPoll(ctx context.Context, id string, params *GetAgentsIdPollParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAgentsIdResultsWithBody request with any body
	PostAgentsIdResultsWithBody(ctx context.Context, id string, params *PostAgentsIdResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAgentsIdResults(ctx context.Context, id string, params *PostAgentsIdResultsParams, body PostAgentsIdResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAgents(ctx context.Context, params *GetAgentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentRegisterWithBody(ctx context.Context, params *PostAgentRegisterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentRegisterRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentRegister(ctx context.Context, params *PostAgentRegisterParams, body PostAgentRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentRegisterRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAgentsId(ctx context.Context, id string, params *DeleteAgentsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAgentsIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAgentsId(ctx context.Context, id string, params *GetAgentsIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentsIdRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentsIdAckWithBody(ctx context.Context, id string, params *PostAgentsIdAckParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentsIdAckRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentsIdAck(ctx context.Context, id string, params *PostAgentsIdAckParams, body PostAgentsIdAckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentsIdAckRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentsIdPing(ctx context.Context, id string, params *PostAgentsIdPingParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentsIdPingRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAgentsIdPoll(ctx context.Context, id string, params *GetAgentsIdPollParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentsIdPollRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentsIdResultsWithBody(ctx context.Context, id string, params *PostAgentsIdResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentsIdResultsRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAgentsIdResults(ctx context.Context, id string, params *PostAgentsIdResultsParams, body PostAgentsIdResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAgentsIdResultsRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAgentsRequest generates requests for GetAgents
func NewGetAgentsRequest(server string, params *GetAgentsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAgentRegisterRequest calls the generic PostAgentRegister builder with application/json body
func NewPostAgentRegisterRequest(server string, params *PostAgentRegisterParams, body PostAgentRegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAgentRegisterRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostAgentRegisterRequestWithBody generates requests for PostAgentRegister with any type of body
func NewPostAgentRegisterRequestWithBody(server string, params *PostAgentRegisterParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAgentsIdRequest generates requests for DeleteAgentsId
func NewDeleteAgentsIdRequest(server string, id string, params *DeleteAgentsIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAgentsIdRequest generates requests for GetAgentsId
func NewGetAgentsIdRequest(server string, id string, params *GetAgentsIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAgentsIdAckRequest calls the generic PostAgentsIdAck builder with application/json body
func NewPostAgentsIdAckRequest(server string, id string, params *PostAgentsIdAckParams, body PostAgentsIdAckJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAgentsIdAckRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewPostAgentsIdAckRequestWithBody generates requests for PostAgentsIdAck with any type of body
func NewPostAgentsIdAckRequestWithBody(server string, id string, params *PostAgentsIdAckParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s/ack", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAgentsIdPingRequest generates requests for PostAgentsIdPing
func NewPostAgentsIdPingRequest(server string, id string, params *PostAgentsIdPingParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s/ping", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAgentsIdPollRequest generates requests for GetAgentsIdPoll
func NewGetAgentsIdPollRequest(server string, id string, params *GetAgentsIdPollParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s/poll", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Count != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "count", runtime.ParamLocationQuery, *params.Count); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAgentsIdResultsRequest calls the generic PostAgentsIdResults builder with application/json body
func NewPostAgentsIdResultsRequest(server string, id string, params *PostAgentsIdResultsParams, body PostAgentsIdResultsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAgentsIdResultsRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewPostAgentsIdResultsRequestWithBody generates requests for PostAgentsIdResults with any type of body
func NewPostAgentsIdResultsRequestWithBody(server string, id string, params *PostAgentsIdResultsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/agents/%s/results", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAgentsWithResponse request
	GetAgentsWithResponse(ctx context.Context, params *GetAgentsParams, reqEditors ...RequestEditorFn) (*GetAgentsResponse, error)

	// PostAgentRegisterWithBodyWithResponse request with any body
	PostAgentRegisterWithBodyWithResponse(ctx context.Context, params *PostAgentRegisterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentRegisterResponse, error)

	PostAgentRegisterWithResponse(ctx context.Context, params *PostAgentRegisterParams, body PostAgentRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentRegisterResponse, error)

	// DeleteAgentsIdWithResponse request
	DeleteAgentsIdWithResponse(ctx context.Context, id string, params *DeleteAgentsIdParams, reqEditors ...RequestEditorFn) (*DeleteAgentsIdResponse, error)

	// GetAgentsIdWithResponse request
	GetAgentsIdWithResponse(ctx context.Context, id string, params *GetAgentsIdParams, reqEditors ...RequestEditorFn) (*GetAgentsIdResponse, error)

	// PostAgentsIdAckWithBodyWithResponse request with any body
	PostAgentsIdAckWithBodyWithResponse(ctx context.Context, id string, params *PostAgentsIdAckParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentsIdAckResponse, error)

	PostAgentsIdAckWithResponse(ctx context.Context, id string, params *PostAgentsIdAckParams, body PostAgentsIdAckJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentsIdAckResponse, error)

	// PostAgentsIdPingWithResponse request
	PostAgentsIdPingWithResponse(ctx context.Context, id string, params *PostAgentsIdPingParams, reqEditors ...RequestEditorFn) (*PostAgentsIdPingResponse, error)

	// GetAgentsIdPollWithResponse request
	GetAgentsIdPollWithResponse(ctx context.Context, id string, params *GetAgentsIdPollParams, reqEditors ...RequestEditorFn) (*GetAgentsIdPollResponse, error)

	// PostAgentsIdResultsWithBodyWithResponse request with any body
	PostAgentsIdResultsWithBodyWithResponse(ctx context.Context, id string, params *PostAgentsIdResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentsIdResultsResponse, error)

	PostAgentsIdResultsWithResponse(ctx context.Context, id string, params *PostAgentsIdResultsParams, body PostAgentsIdResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentsIdResultsResponse, error)
}

type GetAgentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetAgents
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAgentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAgentRegisterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id string `json:"id"`
		Ok bool   `json:"ok"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAgentRegisterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAgentRegisterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAgentsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok bool `json:"ok"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAgentsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAgentsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAgentsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LocalAgent
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAgentsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAgentsIdAckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok bool `json:"ok"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAgentsIdAckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAgentsIdAckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAgentsIdPingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok bool `json:"ok"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAgentsIdPingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAgentsIdPingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAgentsIdPollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]AgentPollTask
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAgentsIdPollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentsIdPollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAgentsIdResultsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Ok bool `json:"ok"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostAgentsIdResultsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAgentsIdResultsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAgentsWithResponse request returning *GetAgentsResponse
func (c *ClientWithResponses) GetAgentsWithResponse(ctx context.Context, params *GetAgentsParams, reqEditors ...RequestEditorFn) (*GetAgentsResponse, error) {
	rsp, err := c.GetAgents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentsResponse(rsp)
}

// PostAgentRegisterWithBodyWithResponse request with arbitrary body returning *PostAgentRegisterResponse
func (c *ClientWithResponses) PostAgentRegisterWithBodyWithResponse(ctx context.Context, params *PostAgentRegisterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentRegisterResponse, error) {
	rsp, err := c.PostAgentRegisterWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentRegisterResponse(rsp)
}

func (c *ClientWithResponses) PostAgentRegisterWithResponse(ctx context.Context, params *PostAgentRegisterParams, body PostAgentRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentRegisterResponse, error) {
	rsp, err := c.PostAgentRegister(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentRegisterResponse(rsp)
}

// DeleteAgentsIdWithResponse request returning *DeleteAgentsIdResponse
func (c *ClientWithResponses) DeleteAgentsIdWithResponse(ctx context.Context, id string, params *DeleteAgentsIdParams, reqEditors ...RequestEditorFn) (*DeleteAgentsIdResponse, error) {
	rsp, err := c.DeleteAgentsId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAgentsIdResponse(rsp)
}

// GetAgentsIdWithResponse request returning *GetAgentsIdResponse
func (c *ClientWithResponses) GetAgentsIdWithResponse(ctx context.Context, id string, params *GetAgentsIdParams, reqEditors ...RequestEditorFn) (*GetAgentsIdResponse, error) {
	rsp, err := c.GetAgentsId(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentsIdResponse(rsp)
}

// PostAgentsIdAckWithBodyWithResponse request with arbitrary body returning *PostAgentsIdAckResponse
func (c *ClientWithResponses) PostAgentsIdAckWithBodyWithResponse(ctx context.Context, id string, params *PostAgentsIdAckParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentsIdAckResponse, error) {
	rsp, err := c.PostAgentsIdAckWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentsIdAckResponse(rsp)
}

func (c *ClientWithResponses) PostAgentsIdAckWithResponse(ctx context.Context, id string, params *PostAgentsIdAckParams, body PostAgentsIdAckJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentsIdAckResponse, error) {
	rsp, err := c.PostAgentsIdAck(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentsIdAckResponse(rsp)
}

// PostAgentsIdPingWithResponse request returning *PostAgentsIdPingResponse
func (c *ClientWithResponses) PostAgentsIdPingWithResponse(ctx context.Context, id string, params *PostAgentsIdPingParams, reqEditors ...RequestEditorFn) (*PostAgentsIdPingResponse, error) {
	rsp, err := c.PostAgentsIdPing(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentsIdPingResponse(rsp)
}

// GetAgentsIdPollWithResponse request returning *GetAgentsIdPollResponse
func (c *ClientWithResponses) GetAgentsIdPollWithResponse(ctx context.Context, id string, params *GetAgentsIdPollParams, reqEditors ...RequestEditorFn) (*GetAgentsIdPollResponse, error) {
	rsp, err := c.GetAgentsIdPoll(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentsIdPollResponse(rsp)
}

// PostAgentsIdResultsWithBodyWithResponse request with arbitrary body returning *PostAgentsIdResultsResponse
func (c *ClientWithResponses) PostAgentsIdResultsWithBodyWithResponse(ctx context.Context, id string, params *PostAgentsIdResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAgentsIdResultsResponse, error) {
	rsp, err := c.PostAgentsIdResultsWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentsIdResultsResponse(rsp)
}

func (c *ClientWithResponses) PostAgentsIdResultsWithResponse(ctx context.Context, id string, params *PostAgentsIdResultsParams, body PostAgentsIdResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAgentsIdResultsResponse, error) {
	rsp, err := c.PostAgentsIdResults(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAgentsIdResultsResponse(rsp)
}

// ParseGetAgentsResponse parses an HTTP response from a GetAgentsWithResponse call
func ParseGetAgentsResponse(rsp *http.Response) (*GetAgentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetAgents
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAgentRegisterResponse parses an HTTP response from a PostAgentRegisterWithResponse call
func ParsePostAgentRegisterResponse(rsp *http.Response) (*PostAgentRegisterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAgentRegisterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id string `json:"id"`
			Ok bool   `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAgentsIdResponse parses an HTTP response from a DeleteAgentsIdWithResponse call
func ParseDeleteAgentsIdResponse(rsp *http.Response) (*DeleteAgentsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAgentsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok bool `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAgentsIdResponse parses an HTTP response from a GetAgentsIdWithResponse call
func ParseGetAgentsIdResponse(rsp *http.Response) (*GetAgentsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LocalAgent
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAgentsIdAckResponse parses an HTTP response from a PostAgentsIdAckWithResponse call
func ParsePostAgentsIdAckResponse(rsp *http.Response) (*PostAgentsIdAckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAgentsIdAckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok bool `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAgentsIdPingResponse parses an HTTP response from a PostAgentsIdPingWithResponse call
func ParsePostAgentsIdPingResponse(rsp *http.Response) (*PostAgentsIdPingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAgentsIdPingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok bool `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAgentsIdPollResponse parses an HTTP response from a GetAgentsIdPollWithResponse call
func ParseGetAgentsIdPollResponse(rsp *http.Response) (*GetAgentsIdPollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentsIdPollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AgentPollTask
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostAgentsIdResultsResponse parses an HTTP response from a PostAgentsIdResultsWithResponse call
func ParsePostAgentsIdResultsResponse(rsp *http.Response) (*PostAgentsIdResultsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAgentsIdResultsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Ok bool `json:"ok"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
